language: node_js
node_js:
- '16.20.2'
env:
  global:
  # REGISTRY_TOKEN(editor=cozy, app=kidizz)
  - secure: pqKNPR73mCdcMghktbgO4jLZov77lC76hQi2jdMrXqG67+EwyXNV2XgLw+Wssn7N03y3rDMpbhkH8DxY155JtGq6RTdm0Y3FjSicCja5YJl1N3yEH9fYOZAWBvx+HPRdAJ221c0mvkkMMdSaIV03RR//P72Y8aM5BajJYeWQJshE3nR95e/IawmU4ALmjuf1F9Yv8Bgm7/d9l6/w1DKPgYDsngH5LnNzC25NFrz4AvmZ5Ys+WnVqqPuh5MsASlootrl0SJl+ik2AD4mcFGHIJquavI52NjCVCM4ZLGXhdPqvVktPgEfUFQOdC9PpOa06rkgrt2uH7sxvOtg9CYYWaJ5HtIOrkKofVfsBrm81NDFgfVE7tTxfeXiR2Gl/8hQmPSc1tRk89yNh1gAVRyejcaml+tdKyCgOCefxL2uOOLVgdIRS6qdkLPnnIr9yHzAlZxgA65D7aNrVs0JHKGvlxy6VG05oHA8AkljuFBkBtYX2TgWhYCSafl2TahPjjLfzSnyKA4UjqtDlRsS4fqb9xqltQPAddSTNxrs2hxEllnwguEDpmUNhXD4A7G4vgfIijNRB3rbGkvru3dAfBtLe898D7j+A8bwaJqHE6Qx/8iM4Jkm+TTtSrDlerY8JjDOl1a8Bfezypz1oOveIkv1XeJlA5bPQbLgrLyPUaia4Bjw=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
